name: deploy frontend

on:
    push:
        branches:
            - master
    release:
        types: [created]

env:
    REGISTRY_HOST: docker.pkg.github.com
    STAGING_URL: http://staging.journali.nl
    STAGING_SERVICE_NAME: journali-staging_web
    PRODUCTION_URL: http://journali.nl
    PRODUCTION_SERVICE_NAME: journali-production_web

jobs:
    deliver:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: publish frontend docker image
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: wesleyklop/journali-frontend/journali-frontend
                  username: ${{ github.actor }}
                  password: ${{ github.token }}
                  registry: ${{ env.REGISTRY_HOST }}
                  tag_semver: true
    deploy:
        name: deploy to an environment
        runs-on: self-hosted
        needs: [deliver]
        steps:
            - name: set environment variables if staging
              if: ${{ github.event_name == 'push' }}
              uses: allenevans/set-env@v1.0.0
              with:
                  SERVICE_NAME: ${{ env.STAGING_SERVICE_NAME }}
                  URL: ${{ env.STAGING_URL }}
                  ENV_NAME: staging
            - name: set environment variables if production
              if: ${{ github.event_name == 'release' }}
              uses: allenevans/set-env@v1.0.0
              with:
                  SERVICE_NAME: ${{ env.PRODUCTION_SERVICE_NAME }}
                  URL: ${{ env.PRODUCTION_URL }}
                  ENV_NAME: production

            - name: login to registry
              run: echo ${{ github.token }} | docker login ${{ env.REGISTRY_HOST }} -u ${{ github.actor }} --password-stdin
            - name: start deployment
              uses: bobheadxi/deployments@master
              id: deployment
              with:
                  step: start
                  token: ${{ github.token }}
                  env: ${{ env.ENV_NAME }}
            - name: run deployment
              run: docker service update --with-registry-auth --force "${SERVICE_NAME}"
            - name: rollback on deployment failure
              if: failure()
              run: docker service rollback "${SERVICE_NAME}"
            - name: update deployment status
              uses: bobheadxi/deployments@master
              if: always()
              with:
                  step: finish
                  token: ${{ github.token }}
                  status: ${{ job.status }}
                  env_url: ${{ env.URL }}
                  deployment_id: ${{ steps.deployment.outputs.deployment_id }}
            - name: logout from registry
              if: always()
              run: docker logout ${{ env.REGISTRY_HOST }}
