name: deploy frontend

on:
    pull_request:
    push:
        branches:
            - master
    release:
        types: [created]

env:
    IMAGE_NAME: wesleyklop/journali-frontend/journali-frontend
    REGISTRY_HOST: docker.pkg.github.com
    STAGING_URL: http://staging.journali.nl
    STAGING_SERVICE_NAME: journali-staging_web
    PRODUCTION_URL: http://journali.nl
    PRODUCTION_SERVICE_NAME: journali-production_web

jobs:
    deliver:
        runs-on: self-hosted
        outputs:
            image: ${{ env.REGISTRY_HOST }}/${{ env.IMAGE_NAME }}:${{ steps.publish.outputs.tag }}
        steps:
            - uses: actions/checkout@v2
            - id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v1
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            - name: publish frontend docker image
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: ${{ env.IMAGE_NAME }}
                  username: ${{ github.actor }}
                  password: ${{ github.token }}
                  registry: ${{ env.REGISTRY_HOST }}
                  tag_semver: true
    deploy:
        name: deploy to an environment
        runs-on: self-hosted
        needs: [deliver]
        steps:
            - name: set environment variables if staging
              if: ${{ github.event_name == 'pull_request' }}
              uses: allenevans/set-env@v1.0.0
              with:
                  SERVICE_NAME: ${{ env.STAGING_SERVICE_NAME }}
                  URL: ${{ env.STAGING_URL }}
                  ENV_NAME: staging
            - name: set environment variables if production
              if: ${{ github.event_name == 'release' }}
              uses: allenevans/set-env@v1.0.0
              with:
                  SERVICE_NAME: ${{ env.PRODUCTION_SERVICE_NAME }}
                  URL: ${{ env.PRODUCTION_URL }}
                  ENV_NAME: production

            - name: login to registry
              run: echo ${{ github.token }} | docker login ${{ env.REGISTRY_HOST }} -u ${{ github.actor }} --password-stdin
            - name: start deployment
              uses: bobheadxi/deployments@master
              id: deployment
              with:
                  step: start
                  token: ${{ github.token }}
                  env: ${{ env.ENV_NAME }}

            # Deploy new frontend version
            - name: deploy new frontend version
              run: |
                  docker service update \
                    --update-failure-action=rollback \
                    --with-registry-auth \
                    --image ${{ needs.deliver.outputs.image }} \
                  ${{ env.SERVICE }}

            - name: update deployment status
              uses: bobheadxi/deployments@master
              if: always()
              with:
                  step: finish
                  token: ${{ github.token }}
                  status: ${{ job.status }}
                  env_url: ${{ env.URL }}
                  deployment_id: ${{ steps.deployment.outputs.deployment_id }}
                  desc: image ${{ needs.deliver.outputs.image }}
            - name: logout from registry
              if: always()
              run: docker logout ${{ env.REGISTRY_HOST }}
